name: Validate renovate config

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  validate:
    name: Validate renovate config
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Validate
        uses: rinchsan/renovate-config-validator@fb9b41c5e259e46902369fc06f8c23f6453a82c6 # renovate: tag=v0.0.8
